import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>LoL Nexus</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className="h-screen w-screen bg-[url('../assets/images/homepage-background-image.jpg')] bg-cover bg-center bg-no-repeat">
        <div className="flex h-full w-full items-center justify-center bg-black bg-opacity-50">
          <section className="bg-white/50 p-2">
            <h1 className="text-center text-7xl font-bold text-white">
              LoL Nexus
            </h1>
            <div></div>
          </section>
        </div>
      </div>
    </>
  );
}
