import React from "react";
import Head from "next/head";
import Image from "next/image";
import { GetServerSideProps } from "next";

const patch = "13.6.1";

type Props = {
  basicPlayerInfo: {
    name: string;
    profileIconId: number;
    summonerLevel: number;
  };
  extraPlayerInfo: [
    {
      tier: string;
      rank: string;
      leaguePoints: number;
      wins: number;
      losses: number;
    }
  ];
  matches: Object[];
};

export default function Player(props: Props) {
  const { basicPlayerInfo, extraPlayerInfo, matches } = props;

  console.log(extraPlayerInfo);

  function winrate() {
    return (
      (extraPlayerInfo[0].wins /
        (extraPlayerInfo[0].wins + extraPlayerInfo[0].losses)) *
      100
    ).toFixed(0);
  }

  return (
    <>
      <Head>
        <title>LoL Nexus</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className="h-screen w-screen overflow-hidden bg-[url('../assets/images/homepage-background-image.jpg')] bg-cover bg-center bg-no-repeat">
        <div className="flex h-full w-full justify-center bg-white bg-opacity-50">
          <section className="flex h-[140px] border border-white bg-violet-500/50 text-gray-100">
            <div className="m-4">
              <Image
                src={`http://ddragon.leagueoflegends.com/cdn/${patch}/img/profileicon/${basicPlayerInfo.profileIconId}.png`}
                width={100}
                height={100}
                alt="Profile Icon"
                className="rounded-2xl shadow"
              />
              <span className="relative left-[34px] bottom-[14px] rounded-2xl bg-violet-500 py-1 px-2 text-xs shadow">
                {basicPlayerInfo.summonerLevel}
              </span>
            </div>
            <div className="m-4">
              <p>{basicPlayerInfo.name}</p>
              <p>{`${extraPlayerInfo[0].tier} ${extraPlayerInfo[0].rank} ${extraPlayerInfo[0].leaguePoints} LP`}</p>
              <p>{`${extraPlayerInfo[0].wins}W ${extraPlayerInfo[0].losses}L`}</p>
              <p>Win Rate {winrate()}%</p>
            </div>
          </section>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async context => {
  const { regionId, player } = context.query;

  // gets basic information about the player.. like their puuid, name, profileIconId, level, etc.
  const res = await fetch(
    `https://${regionId}.api.riotgames.com/lol/summoner/v4/summoners/by-name/${player}?api_key=${process.env.RIOT_API_KEY}`
  );
  const basicPlayerInfo = await res.json();

  // gets extra information about the player.. like their rank, wins, losses, etc.
  const res2 = await fetch(
    `https://${regionId}.api.riotgames.com/lol/league/v4/entries/by-summoner/${basicPlayerInfo.id}?api_key=${process.env.RIOT_API_KEY}`
  );
  const extraPlayerInfo = await res2.json();

  let route = "";
  switch (regionId) {
    case "na1":
    case "br1":
    case "la1":
    case "la2":
      route = "americas";
      break;
    case "kr":
    case "kp1":
      route = "asia";
      break;
    case "eun1":
    case "euw1":
    case "tr1":
    case "ru":
      route = "europe";
      break;
    default:
      break;
  }

  // gets the last x matches the player played
  const res3 = await fetch(
    `https://${route}.api.riotgames.com/lol/match/v5/matches/by-puuid/${basicPlayerInfo.puuid}/ids?count=5&api_key=${process.env.RIOT_API_KEY}`
  );
  const xMatchesId = (await res3.json()) as string[];

  const matches = await Promise.all(
    xMatchesId.map(async matchId => {
      const res3 = await fetch(
        `https://${route}.api.riotgames.com/lol/match/v5/matches/${matchId}?api_key=${process.env.RIOT_API_KEY}`
      );
      const match = await res3.json();

      return match;
    })
  );

  return {
    props: {
      basicPlayerInfo,
      extraPlayerInfo,
      matches
    }
  };
};
