import React from "react";
import Head from "next/head";
import Image from "next/image";
import { GetServerSideProps } from "next";

const patch = "13.6.1";

type Props = {
  basicPlayerInfo: {
    name: string;
    profileIconId: number;
    summonerLevel: number;
    puuid: string;
  };
  extraPlayerInfo: [
    {
      tier: string;
      rank: string;
      leaguePoints: number;
      wins: number;
      losses: number;
    }
  ];
  matches: [
    {
      info: {
        gameCreation: number;
        gameDuration: number;
        gameMode: string;
        gameStartTimestamp: number;
        gameEndTimestamp: number;
        participants: [
          {
            championName: string;
            championLevel: number;
            summonerName: string;
            kills: number;
            deaths: number;
            assists: number;
            profileIcon: number;
            win: boolean;
          }
        ];
      };
    }
  ];
};

export default function Player(props: Props) {
  const { basicPlayerInfo, extraPlayerInfo, matches } = props;

  console.log(matches);

  function winrate() {
    return (
      (extraPlayerInfo[0].wins /
        (extraPlayerInfo[0].wins + extraPlayerInfo[0].losses)) *
      100
    ).toFixed(0);
  }

  function findPlayer(participants: any) {
    const player = participants.find(
      (participant: any) => participant.puuid === basicPlayerInfo.puuid
    );

    return player;
  }

  function gameEndedAgo(time: number) {
    const now = new Date().getTime();
    const difference = now - time;

    const seconds = difference / 1000;
    const minutes = seconds / 60;
    const hours = minutes / 60;
    const days = hours / 24;

    if (seconds >= 0 && seconds < 60) {
      return `${Math.floor(seconds)} seconds ago`;
    } else if (minutes >= 1 && minutes < 60) {
      return `${Math.floor(minutes)} minutes ago`;
    } else if (hours >= 1 && hours < 2) {
      return `an hour ago`;
    } else if (hours >= 2 && hours < 24) {
      return `${Math.floor(hours)} hours ago`;
    } else if (days >= 1 && days < 2) {
      return `a day ago`;
    } else if (days >= 2) {
      return `${Math.floor(days)} days ago`;
    }
  }

  function gameDuration(start: number, end: number) {
    const gameLength = end - start;
    const lengthInMinutes = Math.floor(gameLength / 1000 / 60);
    const lengthInSeconds = Math.floor((gameLength / 1000) % 60);

    return `${lengthInMinutes}m ${lengthInSeconds}s`;
  }

  return (
    <>
      <Head>
        <title>LoL Nexus</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className="h-screen w-screen overflow-hidden bg-[url('../assets/images/homepage-background-image.jpg')] bg-cover bg-center bg-no-repeat">
        <div className="flex h-full w-full flex-col items-center bg-white bg-opacity-50">
          <section className="mb-10 flex h-[140px] rounded border border-white bg-violet-500/50 text-gray-100">
            <div className="m-4 mt-4">
              <Image
                src={`http://ddragon.leagueoflegends.com/cdn/${patch}/img/profileicon/${basicPlayerInfo.profileIconId}.png`}
                width={100}
                height={100}
                alt="Profile Icon"
                className="rounded-2xl shadow"
              />
              <span className="relative left-[34px] bottom-[14px] rounded-2xl bg-violet-500 py-1 px-2 text-xs shadow">
                {basicPlayerInfo.summonerLevel}
              </span>
            </div>
            <div className="m-4">
              <p>{basicPlayerInfo.name}</p>
              <p>{`${extraPlayerInfo[0].tier} ${extraPlayerInfo[0].rank} ${extraPlayerInfo[0].leaguePoints} LP`}</p>
              <p>{`${extraPlayerInfo[0].wins}W ${extraPlayerInfo[0].losses}L`}</p>
              <p>{`Win Rate ${winrate()}%`}</p>
            </div>
          </section>
          <section className="border border-white bg-violet-500/50 p-2">
            {matches.map((match, index) => {
              const player = findPlayer(match.info.participants);
              const timeAgo = gameEndedAgo(match.info.gameEndTimestamp);
              const isWin = player.win ? "Victory" : "Defeat";

              const gameLength = gameDuration(
                match.info.gameStartTimestamp,
                match.info.gameEndTimestamp
              );

              console.log(player);
              return (
                <div
                  key={index}
                  className="mb-2 flex bg-blue-300"
                >
                  <div className="p-2">
                    <p>{match.info.gameMode}</p>
                    <p>{timeAgo}</p>
                    <div className="h-[1px] w-11 bg-gray-100" />
                    <p>{isWin}</p>
                    <p>{gameLength}</p>
                  </div>

                  <div className="p-2">
                    <div className="flex">
                      <Image
                        src={`http://ddragon.leagueoflegends.com/cdn/${patch}/img/champion/${player.championName}.png`}
                        width={50}
                        height={50}
                        alt="Champion Icon"
                      />
                      <div className=""></div>
                    </div>

                    <div></div>
                  </div>
                </div>
              );
            })}
          </section>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async context => {
  const { regionId, player } = context.query;

  // gets basic information about the player.. like their puuid, name, profileIconId, level, etc.
  const res = await fetch(
    `https://${regionId}.api.riotgames.com/lol/summoner/v4/summoners/by-name/${player}?api_key=${process.env.RIOT_API_KEY}`
  );
  const basicPlayerInfo = await res.json();

  // gets extra information about the player.. like their rank, wins, losses, etc.
  const res2 = await fetch(
    `https://${regionId}.api.riotgames.com/lol/league/v4/entries/by-summoner/${basicPlayerInfo.id}?api_key=${process.env.RIOT_API_KEY}`
  );
  const extraPlayerInfo = await res2.json();

  let route = "";
  switch (regionId) {
    case "na1":
    case "br1":
    case "la1":
    case "la2":
      route = "americas";
      break;
    case "kr":
    case "kp1":
      route = "asia";
      break;
    case "eun1":
    case "euw1":
    case "tr1":
    case "ru":
      route = "europe";
      break;
    default:
      break;
  }

  // gets the last x matches the player played
  const res3 = await fetch(
    `https://${route}.api.riotgames.com/lol/match/v5/matches/by-puuid/${basicPlayerInfo.puuid}/ids?count=5&api_key=${process.env.RIOT_API_KEY}`
  );
  const xMatchesId = (await res3.json()) as string[];

  const matches = await Promise.all(
    xMatchesId.map(async matchId => {
      const res3 = await fetch(
        `https://${route}.api.riotgames.com/lol/match/v5/matches/${matchId}?api_key=${process.env.RIOT_API_KEY}`
      );
      const match = await res3.json();

      return match;
    })
  );

  return {
    props: {
      basicPlayerInfo,
      extraPlayerInfo,
      matches
    }
  };
};
